### ISSUE TITLE
Update Database error

### ISSUE THREAD

**Issue by yper3** [JafarAkhondali/Morefixes#2]
Hello, 

After running bash Code/run.sh it completes some processes but gives this database error:

[*] 2024-07-19 02:52:27 - Starting advisory processing
reading fixes ...
(psycopg2.errors.DuplicateTable) relation "hash_unique_constraint" already exists

[SQL: ALTER TABLE commits ADD CONSTRAINT hash_unique_constraint UNIQUE (hash, repo_url);]
(Background on this error at: https://sqlalche.me/e/20/f405)
Unlisted commits: 0

**Comment by JafarAkhondali** [comment]
This error is not important, it's inside the exception:
https://github.com/JafarAkhondali/Morefixes/blob/f6f05ddf9a8006e9708303cd6b378bb070b61306/Code/collect_projects.py#L334

Btw, isn't the dump of the dataset not enough for you? running the dataset takes some time to complete.

There are some steps that I think needs improvement to run for this project. I think you first need to clone https://github.com/github/advisory-database in `Code/resources/advisory-database`

**Comment by yper3** [comment]
thanks for the reply

Yes, I have cloned it, which I always see reported:

Unlisted commits: 0

Does it imply that there are no new elements to insert?

**Comment by JafarAkhondali** [comment]
Can you use the latest dump instead of running the whole project for now? The dump is few months old.

The current version uploaded here might have some bugs and I have some deadlines for other works for now, so it's hard to debug rn

**Comment by JafarAkhondali** [comment]
update: I fixed some bugs& will work on a new dump and publish the fixes & new dump

**Comment by JafarAkhondali** [comment]
@yper3 Fixed in the new version. You can download the new dump from Zenodo. If you want to update the project yourself, please first restore the dump then follow instructions in the readme
